### ISSUE TITLE
Bug when multiple occurences in one line

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/evil-iedit-state#1]
How to reproduce this issue:
1. open up Emacs 
2. delete all the contents of _scratch_ buffer
3. input the following text "that that that that that that that that that that that that that that that "
4. put the cursor under the first "t" character
5. press "v" -> ex/expand-region -> press "e"(enter iedite mode) -> "ciw"

only the first "that" word will be changed, all the other occurences are remaining unchanged.
If I put these "that" in a vertical line, it will work properly.

**Comment by syl20bnr** [comment]
Thank you for the repro steps and sorry for the late reply, I tried in a scratch buffer in elisp major mode and it worked correctly. I tried also by selecting a word in the middle etc...

Do you still have the issue?
What is your version of Emacs and what build of Emacs do you use ?

**Comment by duianto** [comment]
#### Confirmed.

`evil`, `iedit` and `evil-iedit-state` are installed and `init.el` has these entries:
```
(require 'evil)
(evil-mode)
(require 'iedit)
(require 'evil-iedit-state)
```

#### Reproduction steps

1. open and clear the scratch buffer
2. type:
```
that that that
```
3. `M-x er/expand-region RET`
4. `e`
5. `ciw`
6. type: `asdf`

#### Observed

The buffer only shows one instance of `asdf`.

#### When it works

If `iedit-mode` is called instead of pressing `e` in step 4.
`M-x iedit-mode RET`
Then it results in 3 instances of `asdf`.
```
asdf asdf asdf
```

#### System Info

evil-iedit-state-20180607.558
Evil version evil-git-95c2488c6 (evil-20190222.1212)
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
Windows 10 Version 1803

**Comment by syl20bnr** [comment]
Seems to be fixed as per the repo steps. Feel free to reopen if needed.
